server.port=8888
spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///C:/Users/DevoMag/Desktop/config-repo/
eureka.client.enabled=false
spring.cloud.discovery.enabled=false